python3: can't open file '/home/ubuntu/todolist/django-todo/todoApp/manage.py': [Errno 2] No such file or directory
python3: can't open file '/home/ubuntu/todolist/django-todo/todoApp/manage.py': [Errno 2] No such file or directory
